### PR TITLE
Context and filters are now available within shortcode templates.

### LINKED ISSUE #4: TypeError: shortcode_factory() missing 1 required positional argument: 'config'
Function `shortcode_factory()` takes two arguments:

https://github.com/skorokithakis/lektor-shortcodes/blob/e0ee1ba92cba65f3d310be3490137a4eea284ad2/lektor_shortcodes/__init__.py#L33

However, it is called with only one argument:

https://github.com/skorokithakis/lektor-shortcodes/blob/e0ee1ba92cba65f3d310be3490137a4eea284ad2/lektor_shortcodes/__init__.py#L26

As a result, I get the following error when compiling my website:

~~~shell
$ lektor build
Started build
U index.html
  E index.html (TypeError: shortcode_factory() missing 1 required positional argument: 'config')
U about/index.html
  E about/index.html (TypeError: shortcode_factory() missing 1 required positional argument: 'config')
U blog/index.html
E blog/index.html (TypeError: shortcode_factory() missing 1 required positional argument: 'config')
…
Error: Build failed with 10 failures.
Finished build in 0.16 sec
Started prune
Finished prune in 0.01 sec
~~~

# Minimum working example

A minimum working example is available on branch [shortcodes](https://github.com/paternal/lektor-mwe/tree/shortcodes) of project [lektor-mwe](https://github.com/paternal/lektor-mwe). It is a basic blog (built using the default values of `lektor quickstart` paternal/lektor-mwe@c349f9f995cf452deba7abdb138ad07b439d66b6), with shortcodes enabled using the examples from the README (paternal/lektor-mwe@f21b1b41b5596fe65eb5fbcb840fdc313c1bc800).

# Environment

Built on Debian testing (buster), in a virtualenv.

~~~shell
$ python --version
Python 3.6.6
$ lektor --version
Lektor, version 3.1.1
$ pip --version
pip 10.0.1
$ lektor plugins list
shortcodes (version 0.2.5)
~~~

### PR DESCRIPTION
**Pull request by paternal**
Closes #4

I do think this breaks using shortcodes from within jinja2 templates.

### CODE REVIEW

**Comment by paternal** [comment]
⚠️ This might break something. Read the last part of this comment before merging this pull-request. ⚠️

With this pull-request, the environment and context is available from the shortcode template (allowing things like ``{{ this }}`` or ``{{ 'foo'|url }}``.

* Environment (including filters): We pass the lektor environment to the `shortcode_factory()`, to be used (if available).
* Context: Before parsing each page (in `on_markdown_meta_init()`), we remember the current page as `self.lexer._current_context`, to be used in `shorcodes()`. This feels a bit dirty, but I could not find any other way to make `shortcodes()` aware of the current page.

I do think this breaks using shortcodes from jinja2 templates (as documented at the end of the README). But since I did not understand how to use this, I could not test it.

**Comment by paternal** [comment]
Please also note that this pull request might only work with Python3 (and maybe only with python>=3.X, for some X). If you want to merge this pull request, just tell me the supported python versions and I can make it compatible.

**Comment by skorokithakis** [comment]
Thank you for the PR! What's the difference between this and the code in commit 075f849e2b428995facb5bd43382d782f661d3ad? As far as I can see, they're the same?

**Comment by paternal** [comment]
Maybe we can wait for #4 to be sorted out (since we dont get the same behaviour about an even simpler case), but as far as I tested it, neither ``{{ this }}`` nor ``{{ "foo"|url }}`` worked.

**Comment by paternal** [comment]
Additionnal note: I have to test a bit more, but maybe context are mixed when several shortcodes are used in the same page (or maybe not: this bug appeared while I was trying to implement #6). I am waiting for #4 to be sorted out, then I will test this again.

**Comment by skorokithakis** [comment]
Yes, #4 needs to be sorted out ASAP, and I will review the rest afterwards. I need to find a bit of time to test #4, as it doesn't occur on any of my machines, though...

**Comment by skorokithakis** [comment]
Alright, I now understand what's going on here. I think the `*` in your args list is a relatively new Python feature, and I would like to support all versions of Python that Lektor supports. I *think* that includes 2.7?

Apart from that, testing the jinja2 thing at the end of the readme is easy (although the README is a bit wrong/confusing). Just create a section in your config called `test`, like so:

```ini
[test]
foo = bar
```

Then, create a field with the text "This is a [% foo %] here" and display it in your template as `{{ yourfield|shortcodes(section="test") }}`. This will use the shortcode in the `test` section and should show "This is a bar here".

**Comment by skorokithakis** [comment]
It doesn't look to me like this breaks sections, and it looks good other than the backwards-incompatibility issue. If you can fix that and test that sections aren't broken, I think this is good to merge!

**Comment by skorokithakis** [comment]
@paternal Are you available to take a look into the backwards incompatibility issue? We need to support Python 2.7 and above.

**Comment by paternal** [comment]
I've added it to my todo list, but holidays are over, and I no longer *need* this plugin, so it is not a high priority for me…
