### ISSUE TITLE
TypeError: shortcode_factory() missing 1 required positional argument: 'config'

### ISSUE THREAD

**Issue by paternal** [skorokithakis/lektor-shortcodes#4]
Function `shortcode_factory()` takes two arguments:

https://github.com/skorokithakis/lektor-shortcodes/blob/e0ee1ba92cba65f3d310be3490137a4eea284ad2/lektor_shortcodes/__init__.py#L33

However, it is called with only one argument:

https://github.com/skorokithakis/lektor-shortcodes/blob/e0ee1ba92cba65f3d310be3490137a4eea284ad2/lektor_shortcodes/__init__.py#L26

As a result, I get the following error when compiling my website:

~~~shell
$ lektor build
Started build
U index.html
  E index.html (TypeError: shortcode_factory() missing 1 required positional argument: 'config')
U about/index.html
  E about/index.html (TypeError: shortcode_factory() missing 1 required positional argument: 'config')
U blog/index.html
E blog/index.html (TypeError: shortcode_factory() missing 1 required positional argument: 'config')
…
Error: Build failed with 10 failures.
Finished build in 0.16 sec
Started prune
Finished prune in 0.01 sec
~~~

# Minimum working example

A minimum working example is available on branch [shortcodes](https://github.com/paternal/lektor-mwe/tree/shortcodes) of project [lektor-mwe](https://github.com/paternal/lektor-mwe). It is a basic blog (built using the default values of `lektor quickstart` paternal/lektor-mwe@c349f9f995cf452deba7abdb138ad07b439d66b6), with shortcodes enabled using the examples from the README (paternal/lektor-mwe@f21b1b41b5596fe65eb5fbcb840fdc313c1bc800).

# Environment

Built on Debian testing (buster), in a virtualenv.

~~~shell
$ python --version
Python 3.6.6
$ lektor --version
Lektor, version 3.1.1
$ pip --version
pip 10.0.1
$ lektor plugins list
shortcodes (version 0.2.5)
~~~

**Comment by skorokithakis** [comment]
Thanks for the report, I think this is related to the latest Lektor changes. I will issue a release with the fix ASAP.

**Comment by paternal** [comment]
I did some research about this, and a very simple fix is to replace the following line:

https://github.com/skorokithakis/lektor-shortcodes/blob/e0ee1ba92cba65f3d310be3490137a4eea284ad2/lektor_shortcodes/__init__.py#L26

with:

~~~python
 self.compile = shortcode_factory({}, config)
~~~

This would work, but would mean that the context is empty: both ``{{ this }}`` and ``{{ "foo"|url }}`` would rise errors.

A more complex solution can be found in #5.

**Comment by skorokithakis** [comment]
Hm, this is odd, this is working for me. I'm not sure why, maybe because I'm running Lektor 3.1? That's odd...

**Comment by paternal** [comment]
Odd, indeed… Have you tried the minimum working example in branch `shortcodes` of [paternal/lektor-mwe](https://github.com/paternal/lektor-mwe/)?

~~~shell
~$ git clone https://github.com/paternal/lektor-mwe.git
Cloning into 'lektor-mwe'...
remote: Counting objects: 96, done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 96 (delta 27), reused 83 (delta 21), pack-reused 0
Unpacking objects: 100% (96/96), done.
~$ cd lektor-mwe
~/lektor-mwe$ git checkout shortcodes
Branch 'shortcodes' set up to track remote branch 'shortcodes' from 'origin'.
Switched to a new branch 'shortcodes'
~/lektor-mwe$ lektor build
Updating packages in /home/louis/.cache/lektor/packages/62cf2206d7ac8eab5a919bd7c9e83b0e for project
Collecting lektor-shortcodes==0.2.5
Installing collected packages: lektor-shortcodes
Successfully installed lektor-shortcodes-0.2.5
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Started build
U index.html
  E index.html (TypeError: shortcode_factory() missing 1 required positional argument: 'config')
U projects/index.html
  E projects/index.html (TypeError: shortcode_factory() missing 1 required positional argument: 'config')
U about/index.html
  E about/index.html (TypeError: shortcode_factory() missing 1 required positional argument: 'config')
U blog/index.html
  E blog/index.html (TypeError: shortcode_factory() missing 1 required positional argument: 'config')
U static/style.css
U blog/anaconda/index.html
  E blog/anaconda/index.html (TypeError: shortcode_factory() missing 1 required positional argument: 'config')
U blog/boa/index.html
  E blog/boa/index.html (TypeError: shortcode_factory() missing 1 required positional argument: 'config')
U blog/cobra/index.html
  E blog/cobra/index.html (TypeError: shortcode_factory() missing 1 required positional argument: 'config')
U blog/rattlesnake/index.html
  E blog/rattlesnake/index.html (TypeError: shortcode_factory() missing 1 required positional argument: 'config')
U blog/viper/index.html
  E blog/viper/index.html (TypeError: shortcode_factory() missing 1 required positional argument: 'config')
U blog/first-post/index.html
  E blog/first-post/index.html (TypeError: shortcode_factory() missing 1 required positional argument: 'config')
Error: Build failed with 10 failures.
Finished build in 0.17 sec
Started prune
Finished prune in 0.00 sec
~~~

**Comment by skorokithakis** [comment]
Ah, there we go, your MWE worked to reproduce. Thank you, I will debug this ASAP.
